### ISSUE TITLE
minimum and maximum rpm question

### ISSUE THREAD

**Issue by hazcoper** [laurb9/StepperDriver#18]
what is the minimum and maximum rpm?

**Comment by laurb9** [comment]
The upper limit depends on the specs of the motor and the input voltage (usually couple hundred rpm). There's also a theoretical rpm based on the board running the software, but I think that's beyond what steppers can do, so the motor is actually the limiting factor here.

Minimum rpm is 1 because the value is an integer. That's purely a software limitation that seems reasonable enough to me, but is easily overcome.
