### ISSUE TITLE
Pulse width

### ISSUE THREAD

**Issue by Vingell** [laurb9/StepperDriver#41]
(my apologizes if my english isn't good)

Hi,

I have a problem moving my steppers motors using the version 1.1.3. 

I measured the output signal of the arduino and i noticed that the pulse width is lower than the  width in ver 1.1.0, and even lower than ver 1.0.6 (this version is the best for that motors right now). Also the frequency of the pulses is lower.
I changed  step_high_min and i get wider pulses, but even with that the motors doesn't move.

This issue causes a serious problem. I have 2 types of motors, the bigger ones only emit a sharp sound in full step mode using ver 1.1.3 .

**Comment by laurb9** [comment]
I know there may be an issue with the short pulse timing, I kind of hardcoded 1-2us instead of using per-driver settings but I've tried it on some slower ones like the DRV8834 which work fine.

Based on the driver spec sheets I've read, the duty cycle should not be a factor in operation, they all latch on (rising) edge.
