### ISSUE TITLE
enable / sleep / reset controls

### ISSUE THREAD

**Issue by meguia** [laurb9/StepperDriver#5]
Sometimes it is desirable to switch off the motor when there is no need to maintain a holding torque. This can be incorporated in the Basic setup as a single in control that go HIGH for enabling and LOW for disabling the stepper.

**Comment by laurb9** [comment]
Something like this was in the early code but I removed it in commit e1f6618. I thought the driver should not control this line anyway (it should be done externally), so other than wrapping the pin in a set of two methods there is little advantage to having it in the class and require another pin and initializer set. But I'm willing to reconsider.

Also, these drivers have two lines for switching off the motor, ~ENBL and ~SLEEP. One is active LOW the other is active HIGH. While most schematics wire ~SLEEP only, I actually prefer ~ENBL because it does not lose the counter position and does not have a charge wait.

**Comment by feschiessl** [comment]
Thanks for you well-written project. I would actually like to have the enable/sleep functionality as well. It is just convenient to have the additional class function. For my project I did add the function to sent the motor to sleep...

**Comment by laurb9** [comment]
Resolved in #6

**Comment by laurb9** [comment]
One thought about multi-motor setups such as 2-3 axis controls: the ~ENABLE (or ~SLEEP) control line is shared, so it technically doesn't belong to any particular driver.
