### ISSUE TITLE
Dynamically control speed

### ISSUE THREAD

**Issue by finnBsch** [laurb9/StepperDriver#88]
Is it possible to control the speed of a stepper motor with an a4988 driver dynamically? I would like to realize a control system on an arduino, using speed and not position control.
Thanks in advance!

**Comment by laurb9** [comment]
I believe you can use [NonBlocking example](https://github.com/laurb9/StepperDriver/blob/master/examples/NonBlocking/NonBlocking.ino) in constant speed mode and call setRPM() inside the loop to vary the speed.

It's not possible in the other modes because the library will not relinquish control until it's done.
