### ISSUE TITLE
Loosing steps during acceleration and deceleration

### ISSUE THREAD

**Issue by sigurdild** [laurb9/StepperDriver#92]
Is it possible set a cut in and cut out speed during acceleration. I have noticed a step loss and expect it to happen at low rpm during the constant acceleration and deceleration. I can minimise is it to a certain degree by using very high accelerations.

**Comment by laurb9** [comment]
Having a minimum speed could be useful, but I do not understand why slower speed is a problem here.

Are you observing the stepper is losing steps, or is the library sending fewer steps ?
A stepper should be able to handle any slow speed since it's moving step by step. There is a ClockStepper example which does just that, move the stepper one step per second.

**Comment by laurb9** [comment]
Closing (stale)
