### ISSUE TITLE
Allow for Infinite Rotation 

### ISSUE THREAD

**Issue by irl-ops** [laurb9/StepperDriver#98]
**Is your feature request related to a problem? Please describe.**
Eventually the number of degrees of rotation will overflow if you keep adding to it.  

**Describe the solution you'd like**
The option to set a target RPM and direction and the stepper would continue to move until told to stop.  It would be fantastic if you could also optionally use acceleration and deceleration as well.  Keeping track of position in degrees, not number of steps to undo the move, would be nice.  

**Great library!  Thank you for your hard work!**

**Comment by laurb9** [comment]
Using non-blocking mode and constant speed, this is possible to do without changes to the library. It's still better to keep track of the position in steps (modulo 200) because being a float value, the angle may drift over a large number of rotations. The internal step counter of the library does not matter even if rolls over, but care may be needed to it does not land on 0.

**Comment by laurb9** [comment]
Closing, presumed resolved.
